In [1]:
import pandas as pd

In [5]:
# read multiple CSV files and combine them into a single DataFrame
def readListCSV(csv_files):
    df = pd.DataFrame()
    for file in csv_files:
        temp_df = pd.read_csv(file)
        temp_df['_time'] = pd.to_datetime(temp_df['_time'], format='mixed', utc=True)
        # remove the timezone information from the _time column
        temp_df['_time'] = temp_df['_time'].dt.tz_localize(None)
        temp_df['_time'] = temp_df['_time'].dt.strftime('%Y-%m-%d %H:%M:%S')
        temp_df['_time'] = pd.to_datetime(temp_df['_time'])
        #temp_df['_value'] = temp_df['_value'].clip(lower=0, upper=1)  # Ensure _value is binary (0 or 1)
        df = pd.concat([df, temp_df]).drop_duplicates(subset=['_time']).sort_values(by='_time').reset_index(drop=True)
    return df

In [6]:
calefactores_files = ['./climate devices experiments data/calefactores_0.csv', './climate devices experiments data/calefactores_1.csv', 
             './climate devices experiments data/calefactores_2.csv']
df_calefactores = readListCSV(calefactores_files)
df_calefactores

                  _time  _value
0   2026-08-07 06:00:00       1
1   2026-08-07 08:00:00       0
2   2026-08-07 08:00:02       0
3   2026-08-07 08:00:03      -2
4   2026-08-07 08:05:00       1
..                  ...     ...
232 2026-08-26 12:00:04       0
233 2026-08-26 12:00:05       0
234 2026-08-26 16:00:00       1
235 2026-08-26 16:00:12       1
236 2026-08-26 16:00:14       1

[237 rows x 2 columns]

In [7]:
recirculador_files = ['./climate devices experiments data/Recirculador_0.csv', './climate devices experiments data/Recirculador_1.csv']
df_recirculador = readListCSV(recirculador_files)
df_recirculador

                  _time  _value
0   2026-08-06 06:00:00       1
1   2026-08-06 10:00:00       0
2   2026-08-15 22:00:00       1
3   2026-08-15 22:00:17       1
4   2026-08-16 00:00:00       0
..                  ...     ...
168 2026-08-26 09:00:04       0
169 2026-08-26 10:00:10       1
170 2026-08-26 10:00:15       1
171 2026-08-26 12:00:00       0
172 2026-08-26 12:00:02       0

[173 rows x 2 columns]